debug: false
uuid: f6c95fea-f09a-4e43-965e-5df18b2266c0
token_id: 5rNVuiytb3RXmAsZ
token: 2QPIfmPri4dlFTCGxQPjlpBbvTtKRmtOWafClUoMAu8LucCUdRBAs2A87J4dH0pn
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/1ac6-23-97-62-137.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/1ac6-23-97-62-137.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://1ac6-23-97-62-137.ngrok-free.app'
